[package]
name = "mp-client"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mp-protocol = { git = "ssh://git@gitlab.com/andyyu2004/mp-protocol.git" }
mp-protocol = { path = "../mp-protocol" }
clap = {version = "3.0.0-beta.1", features = ["yaml"]}
async-std ={ version = "1.6.0", features = ["attributes"] }
