[package]
name = "mp-server"
version = "0.1.0"
authors = ["andyyu <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11"
# mp-protocol = { git = "ssh://git@gitlab.com/andyyu2004/mp-protocol.git" }
mp-protocol = { path = "../mp-protocol" }
diesel = { version = "1.0.0", features = ["sqlite"] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
taglib = "1"
tokio = { version = "0.2", features = ["full", "uds"] }
id3 = "0.5.1"
